FROM ubuntu
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y nano wget
RUN wget https://download.foldingathome.org/releases/public/release/fahclient/debian-stable-arm64/v7.6/fahclient_7.6.21_arm64.deb && \
    mkdir -p /etc/fahclient && touch /etc/fahclient/config.xml && \
    apt-get install -y ./fahclient_7.6.21_arm64.deb && \
     rm fahclient_7.6.21_arm64.deb

VOLUME [ "/opt/fah/data" ]

WORKDIR /opt/fah
COPY start.sh .

CMD ./start.sh